# This section defines pre-existing resources in customer's VPC
Parameters:
  VPC:
    Type: AWS::EC2::VPC::Id
  KeyPair:
    Type: AWS::EC2::KeyPair::KeyName
  CPMSGName:
    Type: String
    Default: SG Cloud Protection Manager
  CPMInstanceName:
    Type: String
  CPMAMIID:
    Type: String 
  CPMInstanceType:
    Type: String
    Default: t2.small
  CPMSubnetId:
    Type: String

# This section defines CloudFormation resources
Resources:
  # Cloud Protection Manager
  CPMSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Remote access to Cloud Protection Manager
      VpcId:
        Ref: VPC
      Tags: 
        - Key: Name
          Value: !Ref CPMSGName
  CPMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies: 
        - PolicyName: "CPM-Backup"
          PolicyDocument: 
            Statement: 
              - Effect: "Allow"
                Action:
                  - "ec2:CopySnapshot"
                  - "ec2:CopyImage"
                  - "ec2:CreateImage"
                  - "ec2:CreateSnapshot"
                  - "ec2:CreateTags"
                  - "ec2:DeleteSnapshot"
                  - "ec2:DescribeAddresses"
                  - "ec2:DescribeAvailabilityZones"
                  - "ec2:DescribeImageAttribute"
                  - "ec2:DescribeImages"
                  - "ec2:DescribeInstanceAttribute"
                  - "ec2:DescribeInstanceStatus"
                  - "ec2:DescribeInstances"
                  - "ec2:DescribeKeyPairs"
                  - "ec2:DescribePlacementGroups"
                  - "ec2:DescribeRegions"
                  - "ec2:DescribeSecurityGroups"
                  - "ec2:DescribeSnapshotAttribute"
                  - "ec2:DescribeSnapshots"
                  - "ec2:DescribeSubnets"
                  - "ec2:DescribeTags"
                  - "ec2:DescribeVolumeAttribute"
                  - "ec2:DescribeVolumeStatus"
                  - "ec2:DescribeVolumes"
                  - "ec2:DescribeVpcs"
                  - "ec2:ModifyImageAttribute"
                  - "ec2:ModifySnapshotAttribute"
                  - "ec2:ResetSnapshotAttribute"
                  - "kms:ListKeys"
                  - "kms:ListAliases"
                Sid: "Stmt1374236955000"
                Resource: "*"
              - Effect: "Allow"
                Action:
                  - "rds:CreateDBSnapshot"
                  - "rds:DeleteDBSnapshot"
                  - "rds:DescribeDBInstances"
                  - "rds:DescribeDBClusters"
                  - "rds:DescribeDBParameterGroups"
                  - "rds:DescribeDBParameters"
                  - "rds:DescribeDBSnapshots"
                  - "rds:DescribeDBSubnetGroups"
                  - "rds:ListTagsForResource"
                  - "rds:CopyDBSnapshot"
                  - "redshift:DescribeClusters"
                Sid: "Stmt1374237153000"
                Resource: "*"
        - PolicyName: "CPM-Recovery"
          PolicyDocument: 
            Statement: 
              - Effect: "Allow"
                Action:
                  - "ec2:AllocateAddress"
                  - "ec2:AssociateAddress"
                  - "ec2:AttachVolume"
                  - "ec2:CreateImage"
                  - "ec2:CreateVolume"
                  - "ec2:DeleteVolume"
                  - "ec2:DeregisterImage"
                  - "ec2:DescribeImages"
                  - "ec2:DetachVolume"
                  - "ec2:ModifyImageAttribute"
                  - "ec2:ModifyInstanceAttribute"
                  - "ec2:ModifySnapshotAttribute"
                  - "ec2:ModifyVolumeAttribute"
                  - "ec2:RegisterImage"
                  - "ec2:RunInstances"
                  - "ec2:StartInstances"
                  - "ec2:StopInstances"
                  - "iam:PassRole"
                Sid: "Stmt1374243096000"
                Resource: "*"
        - PolicyName: "CPM-SNS"
          PolicyDocument: 
            Statement: 
              - Effect: "Allow"
                Action:
                  - "sns:CreateTopic"
                  - "sns:GetTopicAttributes"
                  - "sns:Publish"
                  - "sns:SetTopicAttributes"
                  - "sns:Subscribe"
                Sid: "Stmt1374246783000"
                Resource: "*"
  CPMConfigInstanceProfile:
      Type: AWS::IAM::InstanceProfile
      Properties:
        Roles:
          - !Ref CPMRole
  CPM01:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref CPMAMIID
      InstanceType: !Ref CPMInstanceType
      KeyName: !Ref KeyPair
      SubnetId:
        - !Ref CPMSubnetId
      SecurityGroupIds:
        - !Ref CPMSecurityGroup
      IamInstanceProfile: !Ref CPMConfigInstanceProfile
      Tags:
        - Key: Name
          Value: !Ref CPMInstanceName
  CPM01EIP01:
    Type: AWS::EC2::EIP
    Properties:
      Domain: VPC
  AssociateCPM01EIP01:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId: !GetAtt CPM01EIP01.AllocationId
      InstanceId: !Ref CPM01
